from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException, Query

from app.config import ENV_FILES, approved_keys
from app.models import (
    AuditEvent,
    AuditLogItem,
    ConfigResponse,
    DiffItem,
    ExecuteRequest,
    ExecuteResponse,
    ExecuteResult,
    PreviewRequest,
    PreviewResponse,
    UpdateTarget,
)
from app.security import AuthUser, get_current_user, require_admin, require_editor
from app.services.audit import audit_service
from app.services.git_provider import GitFile, get_git_provider
from app.services.policy import is_key_allowed
from app.services.rate_limit import rate_limiter
from app.services.repo_registry import repo_registry
from app.services.yaml_engine import patch_yaml
from app.settings import get_settings

router = APIRouter()
settings = get_settings()
provider = get_git_provider()


def _load_target_yaml(target: UpdateTarget, dry_run: bool | None) -> tuple[str, str, GitFile]:
    repo_details = repo_registry.get_repo_details(target.application)
    repo = repo_details["repo"]
    default_branch = repo_details["default_branch"]

    if target.environment_file not in repo_details["files"]:
        raise ValueError(f"File {target.environment_file} not allowed for {target.application}")

    git_file = provider.fetch_file(repo, target.environment_file, default_branch, dry_run=dry_run)
    return repo, default_branch, git_file


def _preview_target(target: UpdateTarget, request: PreviewRequest) -> DiffItem:
    # Preview should reflect the backend's configured mode (real content in live mode).
    repo, _, git_file = _load_target_yaml(target, dry_run=None)
    patch = patch_yaml(git_file.content, request.key_path, request.new_value)
    return DiffItem(
        application=target.application,
        environment_file=target.environment_file,
        repo=repo,
        changed=patch.changed,
        diff=patch.diff,
        updated_yaml=patch.updated_yaml,
    )


def _execute_target(user: AuthUser, target: UpdateTarget, request: ExecuteRequest, effective_dry_run: bool) -> ExecuteResult:
    repo = "unknown"
    try:
        repo, default_branch, git_file = _load_target_yaml(target, dry_run=effective_dry_run)
        patch = patch_yaml(git_file.content, request.key_path, request.new_value)

        if not patch.changed:
            result = ExecuteResult(
                application=target.application,
                repo=repo,
                status="success",
            )
            audit_service.log(
                AuditEvent(
                    user_id=user.user_id,
                    role=user.role,
                    timestamp=datetime.now(timezone.utc),
                    repo=repo,
                    file_path=target.environment_file,
                    key_path=request.key_path,
                    old_value=patch.old_value,
                    new_value=request.new_value,
                    pull_request_url=None,
                    status="success",
                    error=None,
                )
            )
            return result

        branch_suffix = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        branch = f"{settings.branch_prefix}/{user.user_id}/{target.application}/{branch_suffix}-{uuid4().hex[:6]}"
        commit_message = settings.commit_message_template.format(
            key_path=request.key_path,
            environment_file=target.environment_file,
            application=target.application,
        )
        pr_title = f"Automation: update {request.key_path}"
        pr_body = (
            "Automated YAML update generated by DevOps YAML Automation Platform.\n\n"
            f"Application: {target.application}\n"
            f"File: {target.environment_file}\n"
            f"Key: {request.key_path}\n"
            f"Dry run: {str(effective_dry_run).lower()}\n"
        )

        provider.create_branch(repo, default_branch, branch, dry_run=effective_dry_run)
        provider.commit_file(
            repo,
            branch,
            target.environment_file,
            patch.updated_yaml,
            commit_message,
            dry_run=effective_dry_run,
        )
        pr_url = provider.create_pull_request(
            repo,
            branch,
            default_branch,
            pr_title,
            pr_body,
            reviewers=settings.parse_required_reviewers(),
            dry_run=effective_dry_run,
        )

        result = ExecuteResult(
            application=target.application,
            repo=repo,
            branch=branch,
            pull_request_url=pr_url,
            status="success",
        )
        audit_service.log(
            AuditEvent(
                user_id=user.user_id,
                role=user.role,
                timestamp=datetime.now(timezone.utc),
                repo=repo,
                file_path=target.environment_file,
                key_path=request.key_path,
                old_value=patch.old_value,
                new_value=request.new_value,
                pull_request_url=pr_url,
                status="success",
                error=None,
            )
        )
        return result
    except Exception as exc:
        audit_service.log(
            AuditEvent(
                user_id=user.user_id,
                role=user.role,
                timestamp=datetime.now(timezone.utc),
                repo=repo,
                file_path=target.environment_file,
                key_path=request.key_path,
                old_value=None,
                new_value=request.new_value,
                pull_request_url=None,
                status="failed",
                error=str(exc),
            )
        )
        return ExecuteResult(
            application=target.application,
            repo=repo,
            status="failed",
            error=str(exc),
        )


@router.get("/config", response_model=ConfigResponse)
def config_endpoint(user: AuthUser = Depends(get_current_user)) -> ConfigResponse:
    rate_limiter.check(f"{user.user_id}:config")
    return ConfigResponse(
        approved_keys=approved_keys(),
        applications=repo_registry.applications(),
        environment_files=list(ENV_FILES.values()),
    )


@router.get("/audit", response_model=list[AuditLogItem])
def audit_endpoint(
    limit: int = Query(default=200, ge=1, le=1000),
    user: AuthUser = Depends(require_admin),
) -> list[AuditLogItem]:
    rate_limiter.check(f"{user.user_id}:audit")
    return audit_service.list_events(limit=limit)


@router.post("/preview", response_model=PreviewResponse)
def preview(request: PreviewRequest, user: AuthUser = Depends(require_editor)) -> PreviewResponse:
    rate_limiter.check(f"{user.user_id}:preview")

    if not is_key_allowed(request.key_path):
        return PreviewResponse(allowed=False, diffs=[])

    diffs: list[DiffItem] = []
    max_workers = min(max(len(request.targets), 1), 8)
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {pool.submit(_preview_target, target, request): target for target in request.targets}
        for future in as_completed(futures):
            target = futures[future]
            try:
                diffs.append(future.result())
            except Exception as exc:
                diffs.append(
                    DiffItem(
                        application=target.application,
                        environment_file=target.environment_file,
                        repo="unknown",
                        changed=False,
                        diff="",
                        error=str(exc),
                    )
                )

    diffs.sort(key=lambda item: item.application)
    return PreviewResponse(allowed=True, diffs=diffs)


@router.post("/execute", response_model=ExecuteResponse)
def execute(request: ExecuteRequest, user: AuthUser = Depends(require_editor)) -> ExecuteResponse:
    rate_limiter.check(f"{user.user_id}:execute")

    if not is_key_allowed(request.key_path):
        raise HTTPException(status_code=403, detail="Key path is not approved")

    effective_dry_run = settings.dry_run_default if request.dry_run is None else request.dry_run

    results: list[ExecuteResult] = []
    max_workers = min(max(len(request.targets), 1), 8)
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(_execute_target, user, target, request, effective_dry_run): target for target in request.targets
        }
        for future in as_completed(futures):
            results.append(future.result())

    results.sort(key=lambda item: item.application)
    return ExecuteResponse(results=results)
